### ISSUE TITLE
today() vs utcnow()

### ISSUE THREAD

**Issue by brandonmayer-zz** [madsky/dtapi#1]
I find that using datetime.datetime.today() will results in a signature or time api error. When i change line 26 to today = datetime.datetime.utcnow() the api call succeeds. The DT appliance expects the timestamp to be computed relative to GMT or UTC, is it possible your system's localtime() defaults to one of these time zones so today() works for you?

**Comment by madsky** [comment]
Yes, I think you're right.  My Master appliance is in GMT+1, so I assumed that the API time on the appliance would be its local time determined by NTP.  I added the time difference to allow it to be used from anywhere, but it seems that isn't necessary.

**Comment by brandonmayer-zz** [comment]
Got it. From my quick read I had thought tmod was a parameter that would set the temporal state of the device (time window in UI) but your explanation cleared it up. Either way will work but thanks for the interface!
